### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by notsrujangupta**

### CODE REVIEW

**Review by JSpiner — APPROVED** [review]
LGTM

**Comment by JSpiner** [comment]
Because @onemask  is setting up a project, she will merge after setting it.

**Review by onemask — APPROVED** [review]

**Comment by JSpiner** [comment]
oh... sadly our default branch is `master` not main

**Comment by onemask** [comment]
@notsrujangupta 
I merged that PR 🙇‍♀️

**Pull request merged**
